[[redirects]]
  from = "/users"
  to = "https://litejob-backend.herokuapp.com/users"
  status = 200

[[redirects]]
  from = "/oferty"
  to = "https://litejob-backend.herokuapp.com/oferty"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200