"use client"

import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [data, setData] = useState<any>(null);

  useEffect(() => {
    const getData = async () => {
      const res = await fetch("/api/db/mongoose");
      const json = await res.json();
      setData(json);
    };
    getData();
  }, []);

  console.log(data);

  return (
    <>
      <Head>
        <title>LiteJob</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-col gap-12 justify-center items-center min-h-screen">
        <section className="text-8xl font-bold">
          <span>
            <span className="text-teal-400">Lite</span>Job new edition
          </span>
        </section>
        <code className="font-bold text-4xl bg-slate-700 text-slate-100 px-4 py-2 rounded-lg">
          Comming soon
        </code>
        {data && data.map((item: any) => (
          <div key={item._id}>
            <h1>{item.name}</h1>
            <p>{item.slug}</p>
          </div>
        ))}
        <button onClick={() => console.log('elo')}>hej</button>
      </section>
      <footer className="flex justify-center items-center bg-teal-400 p-4">
        <span className="bg-slate-100 rounded-lg text-zinc-900  font-bold py-2 px-4 text-2xl">
          &#169;2023 JaniecParadaise
        </span>
      </footer>
    </>
  );
}
